site_name: Trilha de Estudos
site_dir: ../trilha
theme:
  name: material
  logo: img/favicon.ico
  favicon: img/favicon.ico
  features:
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    # - navigation.expand
plugins:
  - mk-append-to-head:
      append_str: <script id="mcjs">!function (c, h, i, m, p) { m = c.createElement(h), p = c.getElementsByTagName(h)[0], m.async = 1, m.src = i, p.parentNode.insertBefore(m, p) }(document, "script", "https://chimpstatic.com/mcjs-connected/js/users/56ee8d14957b66c343ad9ef19/9850189822702ae565ecaae79.js");</script>
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Introdução:
    - Perguntas frequentes: introducao/faq.md
    - Primeiros passos: introducao/primeiros_passos.md

  - HTML e CSS: html/exercicios.md
  - Javascript:
    - Leitura de códigos: javascript/leitura.md
    - Testando seus primeiros códigos: javascript/testando.md
    - Resolução de problemas: javascript/problemas.md
    - Manipulador de arquivos: javascript/manipulador_arquivos.md
  - Front-end:
    - Manipulação do DOM: front/dom.md
    - Leitura e modificação de códigos: front/leitura.md
    - Interação com uma API fake:
      - Usando uma API client: front/api/client.md
      - Usando Javascript: front/api/javascript.md
      - HTML / CSS / JS: front/api/projeto.md
      - Teste E2E com Playwright: front/api/test.md
  - Back-end:
    - Leitura de códigos: back/leitura.md
    - Servidor API fake: back/api.md
    - Banco de dados: back/database.md
    - Adicionar nova funcionalidade: back/novas_funcionalidades.md
  - Front-end com framework:
    - Leitura: front_framework/leitura.md
    - Exercícios: front_framework/exercicios.md
    - Desafios: front_framework/desafios.md
  - Back-end com framework:
    - Segunda Linguagem: back_framework/segunda_linguagem.md
    - Leitura: back_framework/leitura.md
    - Desafios: back_framework/desafios.md
  - Portfólio:
    - Junior / Pleno: portfolio/junior_pleno.md
    - Senior: portfolio/senior.md